### ISSUE TITLE
ooooo

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/Python-Compiler#1]
oooooo this is going to be exiting, I am 100% going to make issues and pull requests on this one!

**Comment by rayhanadev** [comment]
Lol, I'm just porting some of my better projects over to Github :)
Feel free to make PR's I can't wait to see them!

**Comment by darkdarcool** [comment]
yea(idk much about js, maybe I'll learn, but I will try to understand it to the best of my abilities!)
